### ISSUE TITLE
Feature request - Night weather 

### ISSUE THREAD

**Issue by Khahory** [hanjoongcho/aaf-easydiary#163]
Is it posible to add night weather or any simboly representative for night?  It's prpobably that some users would like it

**Comment by hanjoongcho** [comment]
@Khahory 
There are currently 3 night weather icons available, and if you want more icons, please let us know which one you want from among the icons released for free on the flaticon site.
https://www.flaticon.com/search?word=night%20weather&license=selection

**Comment by Khahory** [comment]
@Prasanta-Hembram mmm but check this...
![Screenshot_20210615-183214_Settings](https://user-images.githubusercontent.com/46386012/122132241-79980c00-ce08-11eb-9310-a750d29fc7ef.png)
![Screenshot_20210615-183154_Easy Diary](https://user-images.githubusercontent.com/46386012/122132247-7ac93900-ce08-11eb-81aa-99310a7d7433.png)

I only see these night weathers

**Comment by hanjoongcho** [comment]
@Khahory 
Are you using the F-Droid version instead of the GooglePlay version?
Due to the licensing policy, the Foss version does not include various icons.
If you use the GooglePlay version, you can use various icons.
![image](https://user-images.githubusercontent.com/7098851/122132900-a6830800-ce76-11eb-9095-f6984ddbcd73.png)

**Comment by Khahory** [comment]
Oohh man, ok i didn't know that, thanks brot.

And yes, I'm using f-droid version
