### ISSUE TITLE
attempt to invoke virtual method void java io output stream.close

### ISSUE THREAD

**Issue by tiqniya** [hanjoongcho/aaf-easydiary#2]
attempt to invoke virtual method void java io output stream.close
share 
when i try to share card
![image](https://user-images.githubusercontent.com/9821159/31940779-33707150-b8b7-11e7-8273-68e10439b8dd.png)

**Comment by tiqniya** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.OutputStream.close()' on a null object reference

**Comment by tiqniya** [comment]
10-24 12:38:50.863 22576-25977/me.blog.korn123.easydiary W/System.err:     at me.blog.korn123.commons.utils.BitmapUtils.saveBitmapToFileCache(BitmapUtils.java:56)
10-24 12:38:50.863 22576-25977/me.blog.korn123.easydiary W/System.err:     at me.blog.korn123.easydiary.activities.PostCardActivity$6.run(PostCardActivity.java:269)

**Comment by hanjoongcho** [comment]
Hi~ tiqniya.

Registered issue are caused by the fact that the working directory has not been initialized.
From android version 6.0 higher, we need to acquire user confirm at runtime, but the working directory is initialized before the privilege is acquired therefore the diary card can not be created.
This problem can be solved by adding the work directory initialization method when generating the diary card after the authorization is completed.
Add the following code to PostCardActivity.java line 269 to generate the working directory to be initialized before calling the BitmapUtils.saveBitmapToFileCache method.
EasyDiaryUtils.initWorkingDirectory(Environment.getExternalStorageDirectory().getAbsolutePath() + Path.USER_CUSTOM_FONTS_DIRECTORY);

If you like, please request a 'pull request' after fixing the issue yourself. =)

**Comment by tiqniya** [comment]
problem solved  by the code you send me.
thank you
