### ISSUE TITLE
Optimize the post card feature by implementing the ability to edit a postcard.

### ISSUE THREAD

**Issue by HarryHeights** [hanjoongcho/aaf-easydiary#47]
I was excited about the postcard feature on the app. I've created quite a handful of postcards already. But, I'd have loved to edit one of them. It was then I realized that it was impossible to do that. I tried editing the content of the diary to see if it would change on the postcard, but it didn't work. That was a dumb move though. 

I'm suggesting that you implement the ability to edit postcards even after saving it. 
Thanks.

**Comment by hanjoongcho** [comment]
Since the post card is an image file, implementation of the requested function is difficult. 
The reason for creating a postcard as an image file is to make a large number of postcards in various forms using color and photo filters in one diary.
Therefore, if the diary is modified, you need to recreate the postcard.😅

**Comment by HarryHeights** [comment]
Oh okay. I understand now.
