### ISSUE TITLE
Merge the security login protocol in one page.

### ISSUE THREAD

**Issue by HarryHeights** [hanjoongcho/aaf-easydiary#49]
It would be good if the pin code and fingerprint security login protocol were merged in a single page. The idea of switching between them doesn't feel so good. Then again, it is impossible to switch back from pin code to fingerprint. 
But, if they were both on the same page, I can use any of the input methods at once.

**Comment by hanjoongcho** [comment]
The reason for implementing the locking feature now is that the following constraints must be considered.
1. If your device does not have fingerprint recognition, you should use pins.
2. If the device has a fingerprint recognition function but the function does not operate suddenly, the pin must be available.

Therefore, all users should make pin setting based on lock function.
In the case of fingerprint recognition, I think that it is a general flow to use it as a purpose of omitting the pin input and unlocking it more easily.

Placing fingerprints and pins on one screen is not a common case.
What do you think?

**Comment by HarryHeights** [comment]
I have seen apps where I could use either pin code or fingerprint at the same time. I understand your point about some phones not having finger print and that's why you separated both security protocol. But, when a user wants to set security up on his/her phone, they should know that their phones don't support fingerprint input. Plus when they toggle on the protocol, they are required to enter their touch ID which is quite impossible.

**Comment by hanjoongcho** [comment]
I think I made a short explanation.
Let's briefly explain locking.

1. PIN must be set to use the lock function.
2. All devices with application installed can be pin locked.
3. If pin lock is set and the device supports fingerprint recognition function, fingerprint setting is possible.
4. Since it is cumbersome to enter the pin number to unlock the pin, you can easily lock it by setting the fingerprint on the device that supports the fingerprint recognition function.
5. Fingerprints are usually an aid to locking and are not used independently.
6. Devices that do not support fingerprinting If a user tries to set up a fingerprint, a message is displayed stating that the function can not be used.
   Therefore, if the device does not provide fingerprint recognition, the user can not set the fingerprint itself.
7. The user who set the fingerprint does not need to show the pin lock screen because he set the fingerprint to unlock easily.
8. The user who set the fingerprint should be provided with a button to change the pin number release screen in consideration of the case that the fingerprint recognition function is broken due to malfunction during application use.

Taking all of the above mentioned locking features together, I conclude that pin locks and fingerprint locks do not have to fit on one screen.
Of course that is my opinion.
Do you need fingerprint recognition and pins on one screen?

**Comment by HarryHeights** [comment]
Wow! Great explanation. Maybe I didn't explain well though.

Okay, let's say that the user's device has a fingerprint hardware. He has set it up. By default when he tries to launch the app, he can use the fingerprint ID and bypass inputting his pin. But maybe he just decides to use the pin code feature, and he clicks on the option use pin code. The pin code page opens up. My suggestion was that, even on that page, it'd be great if the fingerprint ID worked and unlocked the app. Because currently, when I switch to pincode unlock mode, I can't switch back to fingerprint

**Comment by hanjoongcho** [comment]
I will add a screen switching button so that we can return to the fingerprint recognition screen again after changing to the pin unlock screen from the fingerprint screen.

**Comment by HarryHeights** [comment]
Great idea.
