### ISSUE TITLE
Extra security measure for users without fingerprint hardware.

### ISSUE THREAD

**Issue by HarryHeights** [hanjoongcho/aaf-easydiary#51]
I should have made this suggestion alongside my previous suggestion about merging the login protocol. It dawned on me after I noticed that you've implemented that feature. Great job btw.

On the app, users can use either pincode or touch ID. The way it stands right now, only users with fingerprint hardware are at an advantage with two security measures they can choose from. Why not make it even for users with non fingerprint devices by adding pattern security lock.
I think users with none fingerprint devices will fancy it more than the pin code. Plus that's extra security because pattern lock is harder to decipher.

**Comment by hanjoongcho** [comment]
Locking methods with security are PIN, pattern, and password settings.
To be precise, the lock feature provided by the current Easy-Diary is a PIN setting, and the fingerprint function is a convenience feature.

The convenience feature is available only after PIN, pattern, and password are set by default.
If the pattern lock is added, you must select one of PIN and pattern.
You probably will not be using two locks at the same time.

Therefore, if pattern lock function is added, user can set lock method as follows.
01. PIN
02. Pattern
03. PIN + Fingerprint
04. Pattern + Fingerprint

Since adding a lock method is not a high priority, I will implement another function first and proceed.
